#!/bin/bash
monitors=`xrandr --listmonitors | tail -n +2 | sed 's/^.* \(.*\)/\1/'`

for m in $monitors
do
	if [ "$m" != "eDP-1" ]
	then
		xrandr --output $m --auto --left-of eDP-1 --primary --scale 1
	fi
done
