#!/bin/bash
monitors=`xrandr --listmonitors | tail -n +2 | sed 's/^.* \(.*\)/\1/'`

for m in $monitors
do
	if [ "$m" != "eDP-1" ]
	then
		xrandr --output $m --auto --left-of eDP-1 --primary --scale 1
		i3-msg "workspace 2"
		i3-msg "move workspace to output eDP-1"
		i3-msg "workspace 1"
		i3-msg "move workspace to output $m"
		for w in {3..9}
		do
			i3-msg "workspace $w"
			i3-msg "move workspace to output $m"
		done
	fi
done

i3-msg "workspace 1"
