#!/bin/zsh
find autorandr -type f | while read -r file; do
    if [[ $file == *postswitch* ]]; then
        targetDir="$XDG_CONFIG_HOME/$(dirname "$file")"
        mkdir -p "$targetDir"
        ln -s "$(realpath "$file")" "$targetDir/$(basename "$file")"
    fi
done
