#!/bin/bash
localectl set-x11-keymap se '' '' caps:escape
sudo ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
echo "en_US.UTF-8 UTF-8\nsv_SE.UTF-8 UTF-8" | sudo tee /etc/locale.gen
echo "LANG=en_US.UTF-8\nLC_TIME=sv_SE.UTF-8" | sudo tee  /etc/locale.conf
locale-gen
