#!/bin/zsh

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ `echo $TTY | xargs basename | sed 's/tty//'` -ge 4 ]; then
    exit 0
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

autorandr --detected | xargs autorandr --load
picom -f &
feh --no-fehbg --bg-fill /usr/share/backgrounds/archlinux/simple.png &

dunst &
nm-applet &

blockkill="-1"
while [ $blockkill -ne "129" ]
do
    dwmblocks > /dev/null 2>&1
    blockkill=$?
done&

while [ `nmcli networking connectivity` != "full" ]
do
  kill -37 $(pidof dwmblocks)
  sleep 2
done&

dwmkill="-1"
while [ $dwmkill -ne "0" ]
do
    dwm > /dev/null 2>&1
    dwmkill=$?
done

kill -SIGHUP $(pidof dwmblocks)
