#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandr --output eDP-1 --mode 1920x1200 &
picom -f &
feh --bg-fill /usr/share/backgrounds/archlinux/simple.png &

dunst &

blockkill="-1"
while [ $blockkill -ne "129" ]
do
    dwmblocks > /dev/null 2>&1
    blockkill=$?
done&

dwmkill="-1"
while [ $dwmkill -ne "0" ]
do
    dwm > /dev/null 2>&1
    dwmkill=$?
done

kill -SIGHUP $(pidof dwmblocks)
