#!/bin/bash
yarnsourcefile=/etc/apt/sources.list.d/yarn.list

sudo rm -f $yarnsourcefile

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee $yarnsourcefile

sudo apt-get update
sudo apt-get install -y --allow-downgrades --allow-change-held-packages neovim htop tree zsh git-extras tmux silversearcher-ag parallel yarn=1.17.3-1

sudo apt-mark hold yarn
