#!/bin/bash
installer=`./bin/getinstaller`

programs="neovim htop tree zsh tmux parallel hub yarn git"

arch=`lsb_release -a | grep Distributor | grep Arch`

if [ -n "$arch" ]
then
	echo $programs | sudo xargs pacman -Syu --noconfirm --needed the_silver_searcher archlinux-wallpaper reflector nodejs python python-pip
	sudo reflector -c Sweden -a 6 --sort rate --save /etc/pacman.d/mirrorlist
else
	yarnsourcefile=/etc/apt/sources.list.d/yarn.list

	sudo rm -f $yarnsourcefile

	curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
	echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee $yarnsourcefile

	sudo apt-get update
	echo $programs | xargs sudo apt-get install -y  git-extras silversearcher-ag
fi
