#!/bin/bash
yarnsourcefile=/etc/apt/sources.list.d/yarn.list

sudo rm -f $yarnsourcefile

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee $yarnsourcefile

sudo apt update
sudo apt install yarn
