#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <username> <password>"
    exit 1
fi

USERNAME=$1
PASSWORD=$2
HOMEDIR="/home/$USERNAME"

# Check if the home directory exists
if [ -d "$HOMEDIR" ]; then
    echo "Home directory $HOMEDIR exists. Creating user without creating a new home directory."
    useradd -d "$HOMEDIR" -s /bin/zsh -G wheel -M $USERNAME
else
    echo "Home directory $HOMEDIR does not exist. Creating user with a new home directory."
    useradd -m -s /bin/zsh -G wheel $USERNAME
fi

# Set the user's password
echo "$USERNAME:$PASSWORD" | chpasswd

if ! pacman -Q sudo &> /dev/null; then
    echo "sudo is not installed. Installing sudo."
    pacman -S --noconfirm sudo
else
    echo "sudo is already installed."
fi

# Ensure the wheel group has sudo privileges
sed -i '/^# %wheel ALL=(ALL) ALL$/s/^# //' /etc/sudoers

# Configure sudoers to not require a password for the new user
echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

echo "User $USERNAME created and granted sudo privileges."
